version: '3.2'
services:
      wordpress:
        image: wordpress
        restart: always
        ports:
          - 80:80
        environment:
          WORDPRESS_DB_HOST: database
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: root
          WORDPRESS_DB_NAME: dummy 
        volumes:
          - mywords:/var/www/html
      database:
        image: mysql
        restart: always
        volumes:
          - mydatas:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: dummy
volumes:
  mywords:
  mydatas:

